theme: minima
title: alexr notebook
email: alexey.rykhalskiy@gmail.com
description: >
  just a place to write some ideas
baseurl: "" # the subpath of your site, e.g. /blog
url: https://djnzx.github.io
#twitter_username: jekyllrb
github_username: djnzx
linkedin_username: alexey-rykhalskiy
plugins:
  - jekyll/tagging
  - jekyll-feed

tag_page_layout: tag_page
tag_page_dir: tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
